"""
FARIS LangGraph Orchestrator

Consolidated pipeline that uses only 1-2 LLM calls total:
  1. comprehensive_analysis — ONE call for claim extraction + all 6 detectors
  2. remediation — ONE call (conditional, only when risk > 0.3)

Previous architecture made 12+ LLM calls per analysis, which exhausted
Gemini free-tier rate limits after 1-2 analyses and caused every detector
to silently fall back to "no failure" defaults → fake results.
"""

import time
from typing import Any, Optional

from langgraph.graph import StateGraph, END

from app.core.graph.state import AnalysisState, create_initial_state
from app.core.graph.nodes.precheck import precheck_node
from app.core.graph.nodes.comprehensive_analysis import comprehensive_analysis_node
from app.core.graph.nodes.aggregation import aggregation_node
from app.core.graph.nodes.risk_scoring import risk_scoring_node
from app.core.graph.nodes.recommendation import recommendation_node
from app.core.graph.nodes.remediation import remediation_node


def should_continue_after_precheck(state: AnalysisState) -> str:
    """Route after precheck: continue or exit early."""
    if state.get("precheck_passed", False):
        return "comprehensive_analysis"
    return "early_exit"


def early_exit_node(state: AnalysisState) -> dict[str, Any]:
    """Handle early exit when precheck fails."""
    return {
        "failure_detected": False,
        "failure_types": [],
        "detected_failures": [],
        "risk_score": 0.0,
        "risk_level": "low",
        "explanation": f"Analysis skipped: {state.get('precheck_failure_reason', 'Invalid input')}",
        "recommendations": [],
        "end_time": time.time(),
    }


def explanation_passthrough_node(state: AnalysisState) -> dict[str, Any]:
    """
    Explanation is already generated by comprehensive_analysis_node.
    This node only fills in fallback values if they're missing,
    so no LLM call is needed.
    """
    detected_failures = state.get("detected_failures", [])
    risk_score = state.get("risk_score", 0.0)
    risk_level = state.get("risk_level", "low")

    # If comprehensive_analysis already set the explanation, keep it
    if state.get("explanation") and state.get("explanation") != "Analysis complete.":
        return {
            "node_times": {
                **state.get("node_times", {}),
                "explanation": 0.0,
            },
        }

    # Fallback explanation (no LLM call)
    if not detected_failures:
        explanation = (
            f"No significant reliability issues detected. "
            f"Risk score: {risk_score:.2f} ({risk_level})."
        )
    else:
        types = [f["failure_type"].replace("_", " ").title() for f in detected_failures]
        explanation = (
            f"Detected {len(detected_failures)} issue(s): {', '.join(types)}. "
            f"Risk score: {risk_score:.2f} ({risk_level.upper()})."
        )

    return {
        "explanation_summary": explanation,
        "explanation": explanation,
        "key_findings": state.get("key_findings", []),
        "detailed_explanation": explanation,
        "impact_assessment": state.get("impact_assessment", ""),
        "node_times": {
            **state.get("node_times", {}),
            "explanation": 0.0,
        },
    }


def finalize_node(state: AnalysisState) -> dict[str, Any]:
    """Mark analysis end time."""
    return {"end_time": time.time()}


def create_analysis_graph() -> StateGraph:
    """
    Create the FARIS analysis workflow graph.

    Pipeline (max 2 LLM calls):

    START
      │
      ▼
    Precheck (pattern-based, no LLM) ──► Early Exit ──► END
      │
      ▼
    Comprehensive Analysis (1 LLM call — claims + all 6 detectors + explanation)
      │
      ▼
    Aggregation (computation only)
      │
      ▼
    Risk Scoring (computation only)
      │
      ▼
    Explanation Passthrough (no LLM — already done)
      │
      ▼
    Recommendation (DB lookup, no LLM for general domain)
      │
      ▼
    Remediation (1 conditional LLM call if risk > 0.3)
      │
      ▼
    Finalize ──► END
    """
    workflow = StateGraph(AnalysisState)

    # Nodes
    workflow.add_node("precheck", precheck_node)
    workflow.add_node("early_exit", early_exit_node)
    workflow.add_node("comprehensive_analysis", comprehensive_analysis_node)
    workflow.add_node("aggregation", aggregation_node)
    workflow.add_node("risk_scoring", risk_scoring_node)
    workflow.add_node("explanation", explanation_passthrough_node)
    workflow.add_node("recommendation", recommendation_node)
    workflow.add_node("remediation", remediation_node)
    workflow.add_node("finalize", finalize_node)

    # Entry
    workflow.set_entry_point("precheck")

    # Routing
    workflow.add_conditional_edges(
        "precheck",
        should_continue_after_precheck,
        {
            "comprehensive_analysis": "comprehensive_analysis",
            "early_exit": "early_exit",
        },
    )

    # Linear flow
    workflow.add_edge("comprehensive_analysis", "aggregation")
    workflow.add_edge("aggregation", "risk_scoring")
    workflow.add_edge("risk_scoring", "explanation")
    workflow.add_edge("explanation", "recommendation")
    workflow.add_edge("recommendation", "remediation")
    workflow.add_edge("remediation", "finalize")

    # Terminals
    workflow.add_edge("early_exit", END)
    workflow.add_edge("finalize", END)

    return workflow.compile()


# Cached compiled graph
_compiled_graph = None


def get_analysis_graph():
    """Get the compiled analysis graph (cached)."""
    global _compiled_graph
    if _compiled_graph is None:
        _compiled_graph = create_analysis_graph()
    return _compiled_graph


async def run_analysis(
    question: str,
    answer: str,
    context: Optional[str] = None,
    domain: str = "general",
    model_metadata: Optional[dict] = None,
    verified_context: Optional[str] = None,
) -> AnalysisState:
    """
    Run the complete FARIS analysis pipeline.

    Total LLM calls: 1 (analysis) + 0-1 (remediation) = 1-2 max.
    """
    initial_state = create_initial_state(
        question=question,
        answer=answer,
        context=context,
        domain=domain,
        model_metadata=model_metadata,
    )

    if verified_context:
        initial_state["verified_context"] = verified_context

    graph = get_analysis_graph()
    final_state = await graph.ainvoke(initial_state)
    return final_state
